username = "ForgottenLux"
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:7777/callback"
cache_path = "spotify.json"
scope = "user-read-private user-read-email user-top-read user-read-recently-played"